name: "Documentation issue 📄"
description: Report issues on our documentation.
labels: 
- Issue-Docs 
body:
- id: description
  type: textarea
  attributes: 
    label: Describe requested docs changes
    placeholder: Briefly describe which document needs to be corrected and why.
  validations:
    required: true
