# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema
properties:
  assertions:
    - resource: Microsoft.Windows.DSC/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.Windows.DSC/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Community
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: Microsoft.VisualStudio.DSC/AddVSComponents
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS workloads for DevHome
        allowPrerelease: true
      settings:
        ProductId: Microsoft.VisualStudio.Product.Community
        ChannelId: VisualStudio.17.Release
        VsConfigFile: '${WinGetConfigRoot}\..\.vsconfig'
        IncludeRecommended: true
  configurationVersion: 0.2.0