# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/microsoft/PowerToys/blob/main/doc/devdocs/readme.md#compiling-powertoys
properties:
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      id: Enable
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GitHub Desktop
      directives:
        description: Install GitHub Desktop
        allowPrerelease: true
      settings:
        id: GitHub.GitHubDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Visual Studio
      directives:
        description: Install Visual Studio 2022 Community
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: Workloads NativeDesktop
      dependsOn:
        - Visual Studio
      directives:
        description: Install required VS Workloads (NativeDesktop)
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release                  
        components:
          - Microsoft.VisualStudio.Workload.NativeDesktop
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: Workloads Universal
      dependsOn:
        - Visual Studio
      directives:
        description: Install required VS Workloads (Universal)
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release                  
        components:
          - Microsoft.VisualStudio.Workload.Universal
  configurationVersion: 0.2.0