# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

###########################################################################
# This configuration will enable or disable various Windows Settings.     #
# PowerShell module: Microsoft.Windows.Developer (v0.1.3-alpha)           #
###########################################################################

properties:
  resources:
    - resource: Microsoft.Windows.Developer/TaskBarAlignment
      directives:
        description: Set taskbar alignment to left
        allowPrerelease: true
      settings:
        Alignment: Middle # 'Left'
    - resource: Microsoft.Windows.Developer/ShowSecondsInClock
      directives:
        description: Show seconds in clock
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/HideFileExtensions
      directives:
        description: Hide file extensions
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/ShowTaskViewButton
      directives:
        description: Show task view button
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/ShowHiddenFiles
      directives:
        description: Show hidden files
        allowPrerelease: true
      settings:
        Ensure: Absent
    - resource: Microsoft.Windows.Developer/HideTaskBarLabels
      directives:
        description: Never hide task bar labels
        allowPrerelease: true
      settings:
        HideLabels: Always # 'WhenFull', 'Never'
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable dark mode
        allowPrerelease: true
      settings:
        Ensure: Absent
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes
  configurationVersion: 0.2.0
